version: '3.8'
services:
  app:
    image: "viniciusrrabello/pokemon-app:1.0"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - etl
    environment:
      - DB_URL=${DB_URL}
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  etl:
    image: "viniciusrrabello/pokemon-etl:1.0"
    depends_on:
      - postgres
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres
      - DB_URL=${DB_URL}
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge